### PR TITLE
Multiple switch cases with the same block. Additional `do` syntax.

### PR DESCRIPTION
**Pull request by GitSparTV**
```
local a = 1
switch a do
	case 2, 1 then
		print '2 or 1'
	case 3 then
		print("3")
	else
		print("none of them")
end
```

### CODE REVIEW

**Comment by GitSparTV** [comment]
Can't make an ast.array of Id's

**Comment by edubart** [comment]
The `n.Id{{'b'}}` should have been actually `{n.Id{'b'}}` in tests, but as you cannot run the tests with ease, I will take care to fix the renaming issues to merge, thanks!

This is what I had to fix:
https://github.com/edubart/nelua-lang/commit/2f93339bfe978183982ae6cdce619d627642bc52

Do you want to fix this PR to clean commit with those fixes so you shows as the author once merged in contributions, plus this PR will show as "merged" in github, or I can merge manually combining all your 7 commits into a single commit plus the fixes?

**Comment by GitSparTV** [comment]
I will push the fix and see what CI tells me

**Comment by GitSparTV** [comment]
Or I don't need to and it can be merged now?

**Comment by edubart** [comment]
The only thing, is that I don't want to merge 7 commits for a single change, as this will pollute the commit history, I would like that you combine them into a single one, to fix that you need to "squash" the 7 commits into a single one, using `git rebase`. This is a common practice in github for accepting PRs. I could do that here, but then this PR won't show as merged in github, so perhaps you would like to that yourself.

Any remaining issue I can fix in a subsequent commit.

**Comment by edubart** [comment]
Forgot what I told, I just noticed, github now has a "Squash and merge" builtin, didn't notice they built this in the website.

**Comment by edubart** [comment]
Merged!

The only annoyance is that you commit was shown as failing with :x:  in the commit history:
https://github.com/edubart/nelua-lang/commits/master

But no problem because I've fixed in a subsequent one. Thanks for contributing this!

**Comment by GitSparTV** [comment]
Oh cool. Does ❌ in commit history mean something special for a project?

**Comment by edubart** [comment]
Means that the commit in question is *bad* due to broken tests. For me is kinda an aesthetic, I avoid to commit things with broken tests, otherwise people would think that the Nelua master branch is very unstable and should not be trusted. But sometimes this does happen anyway, but when happens I fix asap.

**Comment by GitSparTV** [comment]
Ah, alright. Never used such systems.

**Pull request merged**
