### PR TITLE
(WIP): Libraries page improvement

### PR DESCRIPTION
**Pull request by Andre-LA**
Adding the `vector` library to the Libraries page (copied from the code comments)

Preview: https://andre-la.github.io/nelua-lang/libraries/

### CODE REVIEW

**Comment by edubart** [comment]
It's interesting to add fields also, like
```
| vectorT.size: usize | Number of the elements in the vector. |
| vectorT.data: span(T) | Elements storage of the vector. |
| vectorT.allocator | Allocator of the vector. |
```

**Comment by Andre-LA** [comment]
should `_grow` also be added?

**Comment by edubart** [comment]
@Andre-LA Don't add internal functions, I will remove those from the docs, internal functions are implementation details that can change often and should be avoided.

**Comment by edubart** [comment]
Looks good, once you mark as non draft I will merge.

**Comment by Andre-LA** [comment]
Done :)
(I did some changes `arg`'s and `math`'s compile-time values descriptions)

**Comment by edubart** [comment]
Thanks, merged!

**Pull request merged**
